import { PRIVATE_TOKEN_CURRENCY_TYPE, PRV } from 'constants/token';

export const BLACKLIST_SELL_TOKEN_ID = [
  `${PRV.id}-${PRIVATE_TOKEN_CURRENCY_TYPE.ERC20}`,
  `${PRV.id}-${PRIVATE_TOKEN_CURRENCY_TYPE.BSC_BEP20}`,
];

export const BLACKLIST_PRV = [
  `${PRV.id}-${PRIVATE_TOKEN_CURRENCY_TYPE.PRV}`,
  `${PRV.id}-${PRIVATE_TOKEN_CURRENCY_TYPE.ERC20}`,
  `${PRV.id}-${PRIVATE_TOKEN_CURRENCY_TYPE.BSC_BEP20}`,
];
