export enum POpenseaActionType {
  FETCHING = 'POPENSEA/FETCHING',
  SET_COLLECTIONS = 'POPENSEA/SET_COLLECTIONS',
  SET_SELECTED_COLLECTION = 'POPENSEA/SET_SELECTED_COLLECTION',
  SET_NFTS = 'POPENSEA/SET_NFTS',
  SET_SELECTED_NFT = 'POPENSEA/SET_SELECTED_NFT',
}
